repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.2"
    hooks:
      - id: ruff
        args: ["--fix"]
        # Run on all commits (don't skip when no file-level matches)
        always_run: true
        # Match all files explicitly to avoid platform-specific path issues
        files: ".*"
